### ISSUE TITLE
OAK-D no intrinsic matrix

### ISSUE THREAD

**Issue by vitalijsfescenko** [luxonis/depthai-viewer#54]
The original OAK-D camera has no intrinsic matrix calibration. Is it still supported ? RGB camera output works fine with python API, so camera is not a brick.

**depthai-viewer error**
```
Oak cam:  <depthai_sdk.oak_camera.OakCamera object at 0x7f350bf01750>
Failed to get device properties: There is no Intrinsic matrix available for the the requested cameraID
```

**Reproduce**
*OAK-D: https://shop.luxonis.com/products/oak-d
*Ubuntu 20.04.6 LTS
```
depthai-viewer --version
depthai-viewer 0.1.8 [rustc 1.74.1 (a28077b28 2023-12-04), LLVM 17.0.4] x86_64-unknown-linux-gnu b2c2c42, built 2024-03-01T21:18:41Z
```

**Comment by zrezke** [comment]
@vitalijsfescenko  Interesting, thanks for reporting. You should be able to get it to work by calibrating the device using this procedure: https://docs.luxonis.com/en/latest/pages/calibration/?highlight=calibration

I will also fix the viewer so that if no intrinsics are found a sensible default is assumed - to not error out.

Ran the viewer on a calibrated OAK-D:
![image](https://github.com/luxonis/depthai-viewer/assets/59307111/0d78397a-8f78-4fcb-a887-9524183933ea)

**Comment by vitalijsfescenko** [comment]
Thank you, after calibration it works
