### ISSUE TITLE
OAK-D W PoE - Depth Viewer displays nothing

### ISSUE THREAD

**Issue by dsoltis3** [luxonis/depthai-viewer#67]
Ubuntu 22.04 x86

![Screenshot_2024-06-18_11-06-29](https://github.com/luxonis/depthai-viewer/assets/48269324/99de7a0e-3808-4e4b-9eb5-024a8f1b89c9)

**Comment by wrzwicky** [comment]
Same problem on Windows 11, same pink and red flashing rectangles. Console repeatedly prints:

```
WARNING:root:Ignoring rerun log call: Traceback (most recent call last):
  File "C:\Users\bill\AppData\Local\Programs\DepthAI\venv\lib\site-packages\depthai_viewer\log\log_decorator.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bill\AppData\Local\Programs\DepthAI\venv\lib\site-packages\depthai_viewer\log\rects.py", line 163, in log_rects
    colors = _normalize_colors(colors)
  File "C:\Users\bill\AppData\Local\Programs\DepthAI\venv\lib\site-packages\depthai_viewer\log\__init__.py", line 55, in _normalize_colors
    colors_array = np.array(colors, copy=False)
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

Making the suggested change results in:
* 3D view still flashes a pink image, but the image now has rings around the center.
* The depth cameras still flash pink and red as above, but there are now green boxes identifying things, and the big box moves around as I lean left and right. 

![after np asarray](https://github.com/luxonis/depthai-viewer/assets/12950794/82cdbced-c24d-4b62-a75c-ba816f6aea08)

**Comment by zrezke** [comment]
Hey guys,
I will fix the issue on the viewer right now. It's caused by the release of [Numpy 2.0.0](https://numpy.org/news/#numpy-200-released) which breaks the ABI, this causes undefined behaviour on depthai, like you have experianced... You can fix other examples by installing a version of `numpy < 2.0.0`, like @wrzwicky already posted above.
@wrzwicky  The reason why installing a lower version of numpy did not solve the issue on the viewer is because the viewer creates it's own venv.

**Comment by zrezke** [comment]
Fixed here https://github.com/luxonis/depthai-viewer/releases/tag/v0.2.3
